theme: jekyll-theme-cayman

title: hao xin's blog
description: hao xin's blog.

encoding: utf-8

gems:
  - jekyll-seo-tag

page_meta:
  description: hao xin's blog.

author:
  name: hao xin
  github: haoxins
  email: haoxinst@gmail.com

highlighter: rouge

markdown: kramdown

defaults:
  scope:
    path: articles
    type: pages
  values:
    sectionid: articles
  scope:
    path: _archived
    type: pages
  values:
    sectionid: _archived
